### ISSUE TITLE
Mac OS 10.13.6 can't us it!

### ISSUE THREAD

**Issue by moooyo** [itsuhane/SwitchKey#1]
I don't know why it's happend. but I want use your application in my old mbp. It's the apple's restrict?

**Comment by itsuhane** [comment]
Could you give more information?
How did you use it and how it behaved?

I don't have a 10.13 device so I need some help.

**Comment by itsuhane** [comment]
My mistake. The deployment target was set to 10.14. Now it is fixed.
Could you try the updated release again?

Also please check the new readme and see if the permission is holding you back.

**Comment by moooyo** [comment]
Yes! It's fixed. thank u.
