### ISSUE TITLE
Where is the config file location, for sync/backup purpose

### ISSUE THREAD

**Issue by remiovo** [itsuhane/SwitchKey#18]
Hi,

I want to sync my app list between Macs using `mackup`, but couldn't find any config file of SwitchKey.

I installed with Homebrew and I'm on Mojave.

**Comment by itsuhane** [comment]
Should be at `~/Library/Preferences/itsuhane.tools.SwitchKey.plist`.

**Comment by remiovo** [comment]
Found it, thanks
