### ISSUE TITLE
no add button

### ISSUE THREAD

**Issue by APSRaphael** [itsuhane/SwitchKey#19]
no add button 
![image](https://user-images.githubusercontent.com/22991614/70196569-212c7c80-1744-11ea-837e-4782dfa68b5a.png)
![image](https://user-images.githubusercontent.com/22991614/70196645-6355be00-1744-11ea-8753-0c6d482ef689.png)
![image](https://user-images.githubusercontent.com/22991614/70196656-6e105300-1744-11ea-8315-9af7997d59d4.png)

**Comment by itsuhane** [comment]
I'm still using Mojave. Could it be related with Catalina (#17) ?

**Comment by APSRaphael** [comment]
Probably, U can still click the position where the button is. It's work. Just can't see the button.

**Comment by itsuhane** [comment]
Could you try build from the Xcode project (with Catalina), and see if the add button is still invisible?
