### ISSUE TITLE
Add Current button is invisible on macOS 10.15.2

### ISSUE THREAD

**Issue by wc0517** [itsuhane/SwitchKey#22]
<img width="406" alt="Screen Shot 2019-12-27 at 14 44 15" src="https://user-images.githubusercontent.com/9745635/71505267-842eb080-28b7-11ea-8b05-967a1227a08b.png">

Installed from brew cask.
Have tried reinstallation, can't fix it.

**Comment by itsuhane** [comment]
This happens on Catalina, see #17 and #19.

The latest commit has a working fix.
At this moment, you need to clone/download the code and compile on your own.
I'll make a new release after I upgrade my system.
