### ISSUE TITLE
10.15.2 don't have add button 

### ISSUE THREAD

**Issue by douqq** [itsuhane/SwitchKey#23]
hi:
  I have two issue at my mbp (10.15.2):
  1, when I click the menu icon ,obviously there is a blank but with no buttho(like add ), but it can be clicked and  the function work. 
![https://github.com/douqq/src/blob/master/pic/SwitchKey%20no%20button.png]
   2, My most wanted feature is to set spotlight always use english input , but when I open spotlight search bar(cmd+space) ,then I click switchkey menu icon ,the spotlight close. so how to  achieve this function

**Comment by yunzhang77** [comment]
Actually I am experiencing the same issue here- the "Add Current" option is not visible but I can still "click" it to add my current input source. I am running macOS 10.15.2 on a mbp16.
Thank you for putting the hard work
