### ISSUE TITLE
macOS10.15.3 中内容显示不完整

### ISSUE THREAD

**Issue by waterkon** [itsuhane/SwitchKey#26]
”add current“不显示，但是那个位置是可以被点击有效的。

**Comment by itsuhane** [comment]
请问使用的是 SwitchKey 最新的版本吗？
这个问题出现在 v1.1.1 之前的版本，应该已经在 v1.1.2 修复了。

**Comment by waterkon** [comment]
原来如此，我用的确实是1.1.1更新之后好了。
我是在Google搜索跳出来的第一个结果里https://jinyu.li/switchkey/这个地址下载的，你可以考虑更新一下。
















在 2020-05-28 22:36:50，"jinyu li" <notifications@github.com> 写道：

请问使用的是 SwitchKey 最新的版本吗？
这个问题出现在 v1.1.1 之前的版本，应该已经在 v1.1.2 修复了。
