### ISSUE TITLE
cannot see "delete" and "Add current" button 

### ISSUE THREAD

**Issue by lkl2050** [itsuhane/SwitchKey#27]
![image](https://user-images.githubusercontent.com/10263993/83269735-1a198f00-a1fa-11ea-8ce4-1f40b0cd9ade.png)

My mac version is 10.15.5

**Comment by itsuhane** [comment]
There is no "delete" button.
To remove an item, just select it and press the delete key.

The missing "add current" button has been found back in [v1.1.2](https://github.com/itsuhane/SwitchKey/releases/latest/download/SwitchKey.zip).
You're probably using a prior version.

**Comment by itsuhane** [comment]
I'll close this issue.
Reopen it if my previous answer didn't help.

**Comment by lkl2050** [comment]
The problem is solved. Thank you so much!
