### ISSUE TITLE
launchpad bugs

### ISSUE THREAD

**Issue by zz5678** [itsuhane/SwitchKey#29]
最新版，以及 10.15
四指合拢或者点击切到 launchpad 界面后，如果此时还是 中文输入法状态，开始几次 “直接敲字母” 搜索 app 还是正常的，累积两次到多次后，会出现输入法卡住，点击launchpad 最上面 Search 框，之前敲的字母都还保存在输入法队列，一股脑上屏。

个人觉得如果能加入 launchpad 到 switchkey 切换触发就能解决这个bug -- 或者默认为英文就好，不过目前不知道怎么加 -- launchpad 在 switchkey 里没有窗口列表的设置入口

**Comment by itsuhane** [comment]
Launchpad 的窗口目前是无法检测的 :(
类似的问题在置顶的 issue 里有详情，这个 issue 我就关闭了。
