### ISSUE TITLE
输入法图标显示为黑块

### ISSUE THREAD

**Issue by yakuns** [itsuhane/SwitchKey#3]
如截图显示，应用对应的输入法图标是一个黑块（保存时当前输入法为英文）。这个是正常的还是显示问题？

<img width="344" alt="Screen Shot 2019-05-09 at 10 14 52 AM" src="https://user-images.githubusercontent.com/36554284/57472848-50791a80-7243-11e9-8a47-026165092134.png">

**Comment by itsuhane** [comment]
这不正常。

这个问题可以复现么？

**Comment by empter** [comment]
键盘为U.S/British等国旗图标的时候复现

**Comment by itsuhane** [comment]
原因是彩色输入法图标作为 template 图标绘制。
有没有什么简单的办法判断一个图标是不是 template ，或者判断一个图标是不是单色的？

https://github.com/itsuhane/SwitchKey/blob/350afa5e4c609ae5417fd1356350ed61431deefc/SwitchKey/AppDelegate.swift#L277

**Comment by itsuhane** [comment]
最新版本通过扫描图标的色彩范围进行了判断，已经解决了这个问题。
