### ISSUE TITLE
Any plan to support Apple Silicon M1 Chip?

### ISSUE THREAD

**Issue by tru2dagame** [itsuhane/SwitchKey#35]
Really like this app. 
Do we have any plan to support Apple Silicon M1 Chip?

Thanks.

**Comment by itsuhane** [comment]
At this moment, you can build from the source.
"official" support for M1 chip requires upgrading my toolchain.
Unfortunately I cannot afford doing that right now.

**Comment by tru2dagame** [comment]
@itsuhane Yeah, thanks. I have figured out and built the M1 Chip version locally.

Is there anything I can help? Like create an PR and upload for arm64 version release?

**Comment by itsuhane** [comment]
I've send you an invitation so you can publish a M1 release.

**Comment by tru2dagame** [comment]
Thanks.
Add a new version 1.1.3 for universal app and also created a PR for https://github.com/Homebrew/homebrew-cask/pull/97656
